import type { BlockConfigFieldDefinition, BlockDefinition } from "./graph";

function fields<T extends BlockConfigFieldDefinition[]>(definitions: T): T {
  return definitions;
}

function futureBlock(definition: BlockDefinition): BlockDefinition {
  return {
    visibleInPalette: false,
    implementationStatus: "stub",
    releasePhase: "phase2",
    ...definition,
  };
}

export const blockDefinitions: BlockDefinition[] = [
  {
    type: "chat_input",
    title: "Chat Input",
    category: "Inputs",
    kind: "input",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Accept a live user message as the starting point for a flow.",
    accentColor: "#ff8f70",
    icon: "CI",
    inputs: [],
    outputs: [
      { id: "message", label: "Message", direction: "output", dataTypes: ["chat", "text"] },
    ],
    fields: fields([
      {
        key: "placeholder",
        label: "Placeholder",
        kind: "text",
        description: "Shown when no runtime message is supplied. Runtime message is entered in the Run panel.",
        placeholder: "Ask me anything about your workspace...",
        defaultValue: "Ask me anything about your workspace...",
      },
      {
        key: "persistHistory",
        label: "Persist History",
        kind: "toggle",
        defaultValue: true,
      },
    ]),
  },
  {
    type: "text_input",
    title: "Text Input",
    category: "Inputs",
    kind: "input",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Provide static text, prompts, or seed context into the graph.",
    accentColor: "#ffb36b",
    icon: "TI",
    inputs: [],
    outputs: [
      { id: "text", label: "Text", direction: "output", dataTypes: ["text"] },
    ],
    fields: fields([
      {
        key: "defaultText",
        label: "Default Text",
        kind: "textarea",
        description: "Used as inline document/text content unless a runtime override is provided.",
        placeholder: "Paste text or prompt instructions",
        defaultValue: "",
      },
    ]),
  },
  {
    type: "file_upload",
    title: "File Upload",
    category: "Inputs",
    kind: "input",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Select a local file and push it into the workflow.",
    accentColor: "#f2c66e",
    icon: "FU",
    inputs: [],
    outputs: [
      { id: "file", label: "File", direction: "output", dataTypes: ["file"] },
    ],
    fields: fields([
      {
        key: "accept",
        label: "Accepted Types",
        kind: "text",
        description: "Allowed runtime file extensions. Supported parsers: PDF, DOCX, TXT, CSV, JSON.",
        placeholder: ".pdf,.docx,.txt,.csv,.json",
        defaultValue: ".pdf,.docx,.txt,.csv,.json",
      },
      {
        key: "multiple",
        label: "Allow Multiple",
        kind: "toggle",
        defaultValue: false,
      },
      {
        key: "maxSizeMb",
        label: "Max Size MB",
        kind: "number",
        description: "Per-file limit enforced before the file is saved into local storage.",
        min: 1,
        max: 100,
        step: 1,
        defaultValue: 10,
      },
      {
        key: "defaultLocalPaths",
        label: "Default Local File Paths",
        kind: "textarea",
        description: "Optional fallback paths for demos/tests. Runtime uploads still take priority.",
        placeholder: "storage/sample_company_policy.txt",
        defaultValue: "",
      },
    ]),
  },
  {
    type: "text_extraction",
    title: "Text Extraction",
    category: "Knowledge",
    kind: "knowledge",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Turn uploaded files into chunkable document text.",
    accentColor: "#74d4b6",
    icon: "TE",
    inputs: [
      { id: "file", label: "File", direction: "input", dataTypes: ["file"], required: true },
    ],
    outputs: [
      { id: "document", label: "Document", direction: "output", dataTypes: ["document", "text"] },
    ],
    fields: fields([
      {
        key: "strategy",
        label: "Extraction Strategy",
        kind: "select",
        description: "No OCR yet. Auto uses the local parser for PDF, DOCX, TXT, CSV, or JSON.",
        defaultValue: "auto",
        options: [
          { label: "Automatic", value: "auto" },
          { label: "Plain Text", value: "plain" },
        ],
      },
    ]),
  },
  {
    type: "rag_knowledge",
    title: "RAG Knowledge",
    category: "Knowledge",
    kind: "knowledge",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Embed and retrieve local knowledge from ChromaDB.",
    accentColor: "#57c5a0",
    icon: "RK",
    inputs: [
      { id: "document", label: "Document", direction: "input", dataTypes: ["document", "text"] },
      { id: "query", label: "Query", direction: "input", dataTypes: ["chat", "text"] },
    ],
    outputs: [
      { id: "knowledge", label: "Knowledge", direction: "output", dataTypes: ["knowledge"] },
    ],
    fields: fields([
      {
        key: "ingestMode",
        label: "Mode",
        kind: "select",
        description: "Ingest stores documents in Chroma/SQLite. Retrieve uses the query input to return top chunks.",
        defaultValue: "ingest_and_retrieve",
        options: [
          { label: "Ingest and Retrieve", value: "ingest_and_retrieve" },
          { label: "Ingest Only", value: "ingest_only" },
          { label: "Retrieve Only", value: "retrieve_only" },
        ],
      },
      {
        key: "collection",
        label: "Collection",
        kind: "text",
        description: "Vector collection namespace. Use one collection per knowledge domain.",
        placeholder: "project-notes",
        defaultValue: "default-knowledge",
      },
      {
        key: "chunkSize",
        label: "Chunk Size",
        kind: "number",
        description: "Approximate character size for each retrievable document chunk.",
        min: 100,
        max: 4000,
        step: 50,
        defaultValue: 800,
      },
      {
        key: "overlap",
        label: "Chunk Overlap",
        kind: "number",
        description: "Shared characters between chunks to preserve context across boundaries.",
        min: 0,
        max: 1000,
        step: 10,
        defaultValue: 120,
      },
      {
        key: "topK",
        label: "Top K",
        kind: "number",
        description: "How many source chunks to retrieve for the chatbot.",
        min: 1,
        max: 20,
        step: 1,
        defaultValue: 4,
      },
      {
        key: "tags",
        label: "Tags",
        kind: "text",
        description: "Comma-separated tags stored with chunks and used to filter retrieval.",
        placeholder: "product,docs,internal",
        defaultValue: "",
      },
      {
        key: "allowedFileTypes",
        label: "Allowed File Types",
        kind: "text",
        description: "Documents outside these extensions are ignored during ingestion.",
        placeholder: ".pdf,.docx,.txt,.csv,.json",
        defaultValue: ".pdf,.docx,.txt,.csv,.json",
      },
    ]),
  },
  {
    type: "chatbot",
    title: "Chatbot",
    category: "AI",
    kind: "agent",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Run a conversational agent using an OpenRouter model.",
    accentColor: "#6d9eff",
    icon: "CB",
    inputs: [
      { id: "message", label: "Message", direction: "input", dataTypes: ["chat", "text"], required: true },
      { id: "context", label: "Context", direction: "input", dataTypes: ["knowledge", "text", "json"] },
    ],
    outputs: [
      { id: "reply", label: "Reply", direction: "output", dataTypes: ["chat", "text"] },
      { id: "json", label: "Structured", direction: "output", dataTypes: ["json"] },
    ],
    fields: fields([
      {
        key: "model",
        label: "Model",
        kind: "text",
        description: "OpenRouter model id. This is configurable and not hardcoded by the backend.",
        defaultValue: "openai/gpt-4o-mini",
      },
      {
        key: "systemPrompt",
        label: "System Prompt",
        kind: "textarea",
        description: "Instructions combined with RAG context and optional memory before the user message.",
        placeholder: "You are a helpful, conversational assistant. Answer naturally and cite sources when context is provided.",
        defaultValue: "You are a helpful, conversational assistant. Answer naturally and cite sources when context is provided.",
      },
      {
        key: "answerStyle",
        label: "Answer Style",
        kind: "select",
        description: "Controls whether the chatbot writes a concise chat answer or a more detailed response.",
        defaultValue: "conversational",
        options: [
          { label: "Conversational", value: "conversational" },
          { label: "Concise", value: "concise" },
          { label: "Detailed", value: "detailed" },
        ],
      },
      {
        key: "temperature",
        label: "Temperature",
        kind: "number",
        min: 0,
        max: 2,
        step: 0.1,
        defaultValue: 0.2,
      },
    ]),
  },
  {
    type: "conversation_memory",
    title: "Conversation Memory",
    category: "Memory",
    kind: "memory",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Store and recall conversational context across turns.",
    accentColor: "#9f7aea",
    icon: "CM",
    inputs: [
      { id: "message", label: "Message", direction: "input", dataTypes: ["chat", "text"] },
    ],
    outputs: [
      { id: "memory", label: "Memory", direction: "output", dataTypes: ["memory", "text"] },
    ],
    fields: fields([
      {
        key: "namespace",
        label: "Namespace",
        kind: "text",
        description: "Memory bucket inside the workflow/session/user scope.",
        defaultValue: "default-session",
      },
      {
        key: "windowSize",
        label: "Window Size",
        kind: "number",
        min: 1,
        max: 50,
        step: 1,
        defaultValue: 8,
      },
    ]),
  },
  {
    type: "merge",
    title: "Merge",
    category: "Logic",
    kind: "logic",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Combine multiple streams into a single payload.",
    accentColor: "#ff9f9f",
    icon: "MG",
    inputs: [
      { id: "left", label: "Input A", direction: "input", dataTypes: ["text", "chat", "json", "knowledge", "any"] },
      { id: "right", label: "Input B", direction: "input", dataTypes: ["text", "chat", "json", "knowledge", "any"] },
    ],
    outputs: [
      { id: "merged", label: "Merged", direction: "output", dataTypes: ["text", "json", "any"] },
    ],
    fields: fields([
      {
        key: "mode",
        label: "Mode",
        kind: "select",
        defaultValue: "append",
        options: [
          { label: "Append", value: "append" },
          { label: "JSON Merge", value: "json_merge" },
          { label: "Template", value: "template" },
        ],
      },
    ]),
  },
  {
    type: "condition",
    title: "Condition",
    category: "Logic",
    kind: "logic",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Branch the graph based on boolean or text checks.",
    accentColor: "#ffa65c",
    icon: "CD",
    inputs: [
      { id: "value", label: "Value", direction: "input", dataTypes: ["text", "chat", "boolean", "json"], required: true },
    ],
    outputs: [
      { id: "true", label: "True", direction: "output", dataTypes: ["any"] },
      { id: "false", label: "False", direction: "output", dataTypes: ["any"] },
    ],
    fields: fields([
      {
        key: "expression",
        label: "Expression",
        kind: "text",
        description: "Supported MVP rules: exists, boolean, equals:value, contains:value.",
        placeholder: "contains:approved",
        defaultValue: "contains:approved",
      },
    ]),
  },
  {
    type: "chat_output",
    title: "Chat Output",
    category: "Outputs",
    kind: "output",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Render a conversational response back to the user.",
    accentColor: "#58d68d",
    icon: "CO",
    inputs: [
      { id: "message", label: "Message", direction: "input", dataTypes: ["chat", "text"], required: true },
    ],
    outputs: [],
    fields: fields([
      {
        key: "stream",
        label: "Enable Streaming",
        kind: "toggle",
        defaultValue: true,
      },
    ]),
  },
  {
    type: "json_output",
    title: "JSON Output",
    category: "Outputs",
    kind: "output",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Expose structured output for APIs, tools, or dashboards.",
    accentColor: "#4dd0e1",
    icon: "JO",
    inputs: [
      { id: "payload", label: "Payload", direction: "input", dataTypes: ["json", "text"], required: true },
    ],
    outputs: [],
    fields: fields([
      {
        key: "prettyPrint",
        label: "Pretty Print",
        kind: "toggle",
        defaultValue: true,
      },
    ]),
  },
  {
    type: "dashboard_preview",
    title: "Dashboard/Preview",
    category: "Outputs",
    kind: "output",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Show intermediate state or final results in a visual panel.",
    accentColor: "#7ed3ff",
    icon: "DP",
    inputs: [
      { id: "content", label: "Content", direction: "input", dataTypes: ["text", "json", "preview", "chat"] },
    ],
    outputs: [],
    fields: fields([
      {
        key: "view",
        label: "Preview Mode",
        kind: "select",
        defaultValue: "auto",
        options: [
          { label: "Auto", value: "auto" },
          { label: "Markdown", value: "markdown" },
          { label: "Table", value: "table" },
          { label: "JSON", value: "json" },
        ],
      },
    ]),
  },
  {
    type: "logger",
    title: "Logger",
    category: "System",
    kind: "system",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Capture debug information and execution traces locally.",
    accentColor: "#94a3b8",
    icon: "LG",
    inputs: [
      { id: "payload", label: "Payload", direction: "input", dataTypes: ["any", "text", "json", "chat"] },
    ],
    outputs: [
      { id: "log", label: "Log", direction: "output", dataTypes: ["log"] },
    ],
    fields: fields([
      {
        key: "level",
        label: "Log Level",
        kind: "select",
        defaultValue: "info",
        options: [
          { label: "Debug", value: "debug" },
          { label: "Info", value: "info" },
          { label: "Warn", value: "warn" },
          { label: "Error", value: "error" },
        ],
      },
    ]),
  },
  futureBlock({
    type: "ocr",
    title: "OCR",
    category: "Knowledge",
    kind: "knowledge",
    releasePhase: "phase2",
    description: "Coming soon: convert image-heavy files into extractable text.",
    integrationNotes:
      "Will plug into the parser abstraction and emit the same document payload as Text Extraction.",
    accentColor: "#8ac9ff",
    icon: "OC",
    inputs: [{ id: "file", label: "File", direction: "input", dataTypes: ["file"], required: true }],
    outputs: [{ id: "document", label: "Document", direction: "output", dataTypes: ["document", "text"] }],
    fields: fields([
      { key: "ocrProvider", label: "OCR Provider", kind: "text", defaultValue: "local-ocr" },
      { key: "languageHints", label: "Language Hints", kind: "text", defaultValue: "en" },
    ]),
  }),
  futureBlock({
    type: "summarizer",
    title: "Summarizer",
    category: "AI",
    kind: "agent",
    visibleInPalette: true,
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Summarize extracted text, documents, or retrieved knowledge without a chat UI.",
    integrationNotes:
      "Uses the generic LLM provider and emits both text and structured JSON for formatter/output blocks.",
    accentColor: "#67b8ff",
    icon: "SU",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "document", "knowledge"], required: true }],
    outputs: [{ id: "summary", label: "Summary", direction: "output", dataTypes: ["text", "json"] }],
    fields: fields([
      { key: "model", label: "Model", kind: "text", defaultValue: "openai/gpt-4o-mini", description: "OpenRouter model id used for summarization." },
      { key: "style", label: "Summary Style", kind: "text", defaultValue: "concise bullets", description: "Examples: concise bullets, executive summary, detailed notes." },
      { key: "maxWords", label: "Max Words", kind: "number", defaultValue: 150, min: 20, max: 2000, step: 10 },
    ]),
  }),
  futureBlock({
    type: "classifier",
    title: "Classifier",
    category: "AI",
    kind: "agent",
    visibleInPalette: true,
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Classify extracted content into labels and return structured JSON.",
    integrationNotes:
      "Uses the generic LLM provider and emits JSON that can feed Condition, JSON Output, or Dashboard Preview.",
    accentColor: "#62b6b7",
    icon: "CL",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "document", "chat"], required: true }],
    outputs: [{ id: "classification", label: "Classification", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([
      { key: "model", label: "Model", kind: "text", defaultValue: "openai/gpt-4o-mini" },
      { key: "labels", label: "Labels", kind: "textarea", defaultValue: "policy\ncontract\ninvoice\nsupport\nother", description: "One label per line or comma-separated." },
      { key: "multiLabel", label: "Multi Label", kind: "toggle", defaultValue: false },
    ]),
  }),
  futureBlock({
    type: "extraction_ai",
    title: "Extraction AI",
    category: "AI",
    kind: "agent",
    visibleInPalette: true,
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Extract structured JSON fields from documents or text.",
    integrationNotes:
      "Designed to sit after Text Extraction and feed JSON Output, Dashboard Preview, or downstream logic.",
    accentColor: "#6ad3c8",
    icon: "EA",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "document"], required: true }],
    outputs: [{ id: "json", label: "JSON", direction: "output", dataTypes: ["json"] }],
    fields: fields([
      { key: "model", label: "Model", kind: "text", defaultValue: "openai/gpt-4o-mini" },
      { key: "schemaPrompt", label: "Schema / Fields To Extract", kind: "textarea", defaultValue: "Return JSON with keys: title, summary, important_dates, action_items, risks", description: "Describe the JSON object you want back." },
      { key: "strictMode", label: "Strict Mode", kind: "toggle", defaultValue: true },
    ]),
  }),
  {
    type: "prompt_template",
    title: "Prompt Template",
    category: "AI",
    kind: "agent",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Turn upstream values into a clean reusable prompt with {{variables}}.",
    accentColor: "#5b8def",
    icon: "PT",
    inputs: [{ id: "variables", label: "Variables", direction: "input", dataTypes: ["text", "json", "chat", "document", "knowledge", "any"] }],
    outputs: [{ id: "prompt", label: "Prompt", direction: "output", dataTypes: ["text"] }],
    fields: fields([
      { key: "template", label: "Template", kind: "textarea", defaultValue: "Use this input and produce a useful result:\n\n{{input}}" },
    ]),
  },
  {
    type: "document_splitter",
    title: "Document Splitter",
    category: "Knowledge",
    kind: "knowledge",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Split long documents into sections for extraction, loops, or exports.",
    accentColor: "#43c6ac",
    icon: "DS",
    inputs: [{ id: "document", label: "Document", direction: "input", dataTypes: ["document", "text"], required: true }],
    outputs: [{ id: "sections", label: "Sections", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([
      { key: "mode", label: "Split Mode", kind: "select", defaultValue: "paragraphs", options: [{ label: "Paragraphs", value: "paragraphs" }, { label: "Headings", value: "headings" }] },
      { key: "maxChars", label: "Max Chars", kind: "number", defaultValue: 1200, min: 200, max: 8000, step: 100 },
    ]),
  },
  {
    type: "table_extractor",
    title: "Table Extractor",
    category: "Knowledge",
    kind: "knowledge",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Extract simple CSV, pipe, or tabular text into JSON rows.",
    accentColor: "#39b7dd",
    icon: "TX",
    inputs: [{ id: "document", label: "Document", direction: "input", dataTypes: ["document", "text"], required: true }],
    outputs: [{ id: "tables", label: "Tables", direction: "output", dataTypes: ["json"] }],
    fields: fields([
      { key: "delimiter", label: "Delimiter", kind: "select", defaultValue: "auto", options: [{ label: "Auto", value: "auto" }, { label: "Comma", value: "," }, { label: "Pipe", value: "|" }, { label: "Tab", value: "\t" }] },
    ]),
  },
  {
    type: "schema_validator",
    title: "Schema Validator",
    category: "Logic",
    kind: "logic",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Check JSON output for required keys before sending it downstream.",
    accentColor: "#f6ad55",
    icon: "SV",
    inputs: [{ id: "payload", label: "Payload", direction: "input", dataTypes: ["json", "text"], required: true }],
    outputs: [{ id: "validation", label: "Validation", direction: "output", dataTypes: ["json", "boolean"] }],
    fields: fields([
      { key: "requiredKeys", label: "Required Keys", kind: "textarea", defaultValue: "title\nsummary" },
    ]),
  },
  {
    type: "retry_fallback_llm",
    title: "Retry/Fallback LLM",
    category: "AI",
    kind: "agent",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Call an LLM with retries and a fallback model for more resilient workflows.",
    accentColor: "#7c8cff",
    icon: "RF",
    inputs: [{ id: "prompt", label: "Prompt", direction: "input", dataTypes: ["text", "chat"], required: true }],
    outputs: [
      { id: "reply", label: "Reply", direction: "output", dataTypes: ["chat", "text"] },
      { id: "json", label: "Telemetry", direction: "output", dataTypes: ["json"] },
    ],
    fields: fields([
      { key: "model", label: "Primary Model", kind: "text", defaultValue: "openai/gpt-4o-mini" },
      { key: "fallbackModel", label: "Fallback Model", kind: "text", defaultValue: "openai/gpt-4o-mini" },
      { key: "systemPrompt", label: "System Prompt", kind: "textarea", defaultValue: "You are a reliable assistant." },
      { key: "temperature", label: "Temperature", kind: "number", defaultValue: 0.2, min: 0, max: 2, step: 0.1 },
      { key: "maxRetries", label: "Max Retries", kind: "number", defaultValue: 1, min: 0, max: 5, step: 1 },
    ]),
  },
  {
    type: "citation_formatter",
    title: "Citation Formatter",
    category: "Outputs",
    kind: "output",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Turn RAG/chat citations into a clean source list.",
    accentColor: "#65d6ad",
    icon: "CF",
    inputs: [{ id: "sources", label: "Sources", direction: "input", dataTypes: ["knowledge", "chat", "json"], required: true }],
    outputs: [
      { id: "text", label: "Text", direction: "output", dataTypes: ["text"] },
      { id: "json", label: "JSON", direction: "output", dataTypes: ["json"] },
    ],
    fields: fields([
      { key: "style", label: "Style", kind: "select", defaultValue: "numbered", options: [{ label: "Numbered", value: "numbered" }, { label: "Bullets", value: "bullets" }] },
    ]),
  },
  {
    type: "form_input",
    title: "Form Input",
    category: "Inputs",
    kind: "input",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Capture structured app input as JSON for downstream blocks.",
    accentColor: "#ffbd59",
    icon: "FI",
    inputs: [],
    outputs: [
      { id: "json", label: "JSON", direction: "output", dataTypes: ["json"] },
      { id: "text", label: "Text", direction: "output", dataTypes: ["text"] },
    ],
    fields: fields([
      { key: "fields", label: "Fields", kind: "textarea", defaultValue: "name:text\nemail:text\nrequest:textarea" },
      { key: "defaultValues", label: "Default Values JSON", kind: "textarea", defaultValue: "{\"name\":\"Demo User\",\"request\":\"Summarize this.\"}" },
    ]),
  },
  {
    type: "webhook_trigger",
    title: "Webhook Trigger",
    category: "Inputs",
    kind: "input",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Start a workflow from a JSON payload sample or runtime body.",
    accentColor: "#ff9f68",
    icon: "WH",
    inputs: [],
    outputs: [{ id: "payload", label: "Payload", direction: "output", dataTypes: ["json"] }],
    fields: fields([
      { key: "samplePayload", label: "Sample Payload", kind: "textarea", defaultValue: "{\"event\":\"created\",\"text\":\"Hello from webhook\"}" },
    ]),
  },
  {
    type: "http_request",
    title: "HTTP Request",
    category: "System",
    kind: "system",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Prepare an external API request payload. External sending is disabled by default.",
    accentColor: "#7785ff",
    icon: "HR",
    inputs: [{ id: "body", label: "Body", direction: "input", dataTypes: ["json", "text", "any"] }],
    outputs: [{ id: "response", label: "Response", direction: "output", dataTypes: ["json"] }],
    fields: fields([
      { key: "method", label: "Method", kind: "select", defaultValue: "POST", options: [{ label: "GET", value: "GET" }, { label: "POST", value: "POST" }, { label: "PUT", value: "PUT" }] },
      { key: "url", label: "URL", kind: "text", defaultValue: "https://example.com/api" },
      { key: "enableRequest", label: "Enable External Request", kind: "toggle", defaultValue: false },
    ]),
  },
  {
    type: "data_mapper",
    title: "Data Mapper",
    category: "Logic",
    kind: "logic",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Rename and reshape JSON fields between blocks.",
    accentColor: "#ff9f9f",
    icon: "DM",
    inputs: [{ id: "input", label: "Input", direction: "input", dataTypes: ["json", "text", "any"], required: true }],
    outputs: [{ id: "mapped", label: "Mapped", direction: "output", dataTypes: ["json"] }],
    fields: fields([
      { key: "mappings", label: "Mappings", kind: "textarea", defaultValue: "extracted.summary:summary\nextracted.risks:risks" },
    ]),
  },
  {
    type: "loop_for_each",
    title: "Loop / For Each",
    category: "Logic",
    kind: "logic",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Normalize lists, rows, sections, or matches into iterable items.",
    accentColor: "#f59e0b",
    icon: "LF",
    inputs: [{ id: "items", label: "Items", direction: "input", dataTypes: ["json", "text", "any"], required: true }],
    outputs: [{ id: "items", label: "Items", direction: "output", dataTypes: ["json"] }],
    fields: fields([{ key: "limit", label: "Limit", kind: "number", defaultValue: 25, min: 1, max: 500, step: 1 }]),
  },
  {
    type: "approval_step",
    title: "Approval Step",
    category: "Logic",
    kind: "logic",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "MVP human approval gate with configurable default decision.",
    accentColor: "#ff9b5c",
    icon: "AP",
    inputs: [{ id: "request", label: "Request", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [
      { id: "approved", label: "Approved", direction: "output", dataTypes: ["any"] },
      { id: "rejected", label: "Rejected", direction: "output", dataTypes: ["any"] },
    ],
    fields: fields([
      { key: "defaultDecision", label: "Default Decision", kind: "select", defaultValue: "approved", options: [{ label: "Approved", value: "approved" }, { label: "Rejected", value: "rejected" }] },
    ]),
  },
  {
    type: "email_sender",
    title: "Email Sender",
    category: "Outputs",
    kind: "output",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Prepare an email payload for future provider delivery.",
    accentColor: "#ffb347",
    icon: "ES",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [{ id: "status", label: "Status", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([
      { key: "to", label: "To", kind: "text", defaultValue: "reviewer@example.com" },
      { key: "subject", label: "Subject", kind: "text", defaultValue: "AI Studio workflow result" },
    ]),
  },
  {
    type: "slack_notification",
    title: "Slack/Teams Notification",
    category: "Outputs",
    kind: "output",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Prepare a team notification payload for Slack, Teams, Discord, or webhook adapters.",
    accentColor: "#ffc36f",
    icon: "SN",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [{ id: "status", label: "Status", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([{ key: "channel", label: "Channel", kind: "text", defaultValue: "#ai-studio" }]),
  },
  {
    type: "database_writer",
    title: "Database Writer",
    category: "System",
    kind: "system",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Capture structured rows as local run evidence for later database adapters.",
    accentColor: "#5d9cef",
    icon: "DW",
    inputs: [{ id: "row", label: "Row", direction: "input", dataTypes: ["json", "text", "any"], required: true }],
    outputs: [{ id: "record", label: "Record", direction: "output", dataTypes: ["json"] }],
    fields: fields([{ key: "table", label: "Table", kind: "text", defaultValue: "workflow_results" }]),
  },
  {
    type: "csv_excel_export",
    title: "CSV/Excel Export",
    category: "Outputs",
    kind: "output",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Export rows or structured data to a local CSV file.",
    accentColor: "#4dd0e1",
    icon: "CE",
    inputs: [{ id: "data", label: "Data", direction: "input", dataTypes: ["json", "text", "any"], required: true }],
    outputs: [{ id: "file", label: "File", direction: "output", dataTypes: ["file", "json"] }],
    fields: fields([{ key: "filename", label: "Filename", kind: "text", defaultValue: "workflow-export.csv" }]),
  },
  {
    type: "pii_redactor",
    title: "PII Redactor",
    category: "System",
    kind: "system",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Mask emails and phone numbers before LLM or export steps.",
    accentColor: "#f26b6b",
    icon: "PR",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [
      { id: "redacted", label: "Redacted", direction: "output", dataTypes: ["text"] },
      { id: "json", label: "Stats", direction: "output", dataTypes: ["json"] },
    ],
    fields: fields([
      { key: "redactEmails", label: "Redact Emails", kind: "toggle", defaultValue: true },
      { key: "redactPhones", label: "Redact Phones", kind: "toggle", defaultValue: true },
    ]),
  },
  {
    type: "router_switch",
    title: "Router / Switch",
    category: "Logic",
    kind: "logic",
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Route payloads by matching route names in the input text.",
    accentColor: "#ffa65c",
    icon: "RS",
    inputs: [{ id: "input", label: "Input", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [{ id: "route", label: "Route", direction: "output", dataTypes: ["any"] }],
    fields: fields([
      { key: "routes", label: "Routes", kind: "textarea", defaultValue: "urgent\nbilling\ntechnical\ndefault" },
      { key: "defaultRoute", label: "Default Route", kind: "text", defaultValue: "default" },
    ]),
  },
  futureBlock({
    type: "intent_router",
    title: "Intent Router",
    category: "Logic",
    kind: "logic",
    releasePhase: "phase2",
    description: "Coming soon: route requests to different branches by intent.",
    integrationNotes:
      "Will extend the condition/router pattern and emit named route outputs for downstream branches.",
    accentColor: "#ffb067",
    icon: "IR",
    inputs: [{ id: "message", label: "Message", direction: "input", dataTypes: ["chat", "text"], required: true }],
    outputs: [
      { id: "primary", label: "Primary Route", direction: "output", dataTypes: ["any"] },
      { id: "fallback", label: "Fallback Route", direction: "output", dataTypes: ["any"] },
    ],
    fields: fields([
      { key: "routes", label: "Routes", kind: "textarea", defaultValue: "support\nsales\nfallback" },
      { key: "defaultRoute", label: "Default Route", kind: "text", defaultValue: "fallback" },
    ]),
  }),
  futureBlock({
    type: "web_search",
    title: "Web Search",
    category: "Knowledge",
    kind: "knowledge",
    releasePhase: "phase2",
    description: "Coming soon: fetch web search results as live context.",
    integrationNotes:
      "Will call a search provider and emit knowledge payloads compatible with RAG and Chatbot blocks.",
    accentColor: "#6bc4ff",
    icon: "WS",
    inputs: [{ id: "query", label: "Query", direction: "input", dataTypes: ["chat", "text"], required: true }],
    outputs: [{ id: "results", label: "Results", direction: "output", dataTypes: ["knowledge", "json"] }],
    fields: fields([
      { key: "provider", label: "Search Provider", kind: "text", defaultValue: "tbd-search" },
      { key: "topK", label: "Top K", kind: "number", defaultValue: 5, min: 1, max: 20, step: 1 },
    ]),
  }),
  futureBlock({
    type: "web_page_reader",
    title: "Web Page Reader",
    category: "Knowledge",
    kind: "knowledge",
    releasePhase: "phase2",
    description: "Coming soon: read and normalize web page content.",
    integrationNotes:
      "Will accept URLs, fetch page content, and emit document payloads for RAG or summarization.",
    accentColor: "#6fcbff",
    icon: "WR",
    inputs: [{ id: "url", label: "URL", direction: "input", dataTypes: ["text"], required: true }],
    outputs: [{ id: "document", label: "Document", direction: "output", dataTypes: ["document", "text"] }],
    fields: fields([
      { key: "readerMode", label: "Reader Mode", kind: "select", defaultValue: "clean", options: [{ label: "Clean", value: "clean" }, { label: "Raw", value: "raw" }] },
    ]),
  }),
  futureBlock({
    type: "publish_api",
    title: "Publish API",
    category: "System",
    kind: "system",
    releasePhase: "phase3",
    description: "Coming soon: publish workflows as authenticated APIs.",
    integrationNotes:
      "Will build on the current publish scaffolding with versioned endpoints, auth, and contracts.",
    accentColor: "#8aa2ff",
    icon: "PA",
    inputs: [{ id: "workflow", label: "Workflow", direction: "input", dataTypes: ["json", "any"] }],
    outputs: [{ id: "endpoint", label: "Endpoint", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([
      { key: "apiName", label: "API Name", kind: "text", defaultValue: "published-workflow" },
      { key: "authMode", label: "Auth Mode", kind: "text", defaultValue: "api-key" },
    ]),
  }),
  futureBlock({
    type: "error_handler",
    title: "Error Handler",
    category: "System",
    kind: "system",
    releasePhase: "phase2",
    description: "Coming soon: catch failures and redirect execution to recovery paths.",
    integrationNotes:
      "Will wrap execution nodes and expose structured retry/fallback semantics for the graph engine.",
    accentColor: "#ff8a8a",
    icon: "EH",
    inputs: [{ id: "error", label: "Error", direction: "input", dataTypes: ["json", "text", "any"] }],
    outputs: [{ id: "recovered", label: "Recovered", direction: "output", dataTypes: ["any"] }],
    fields: fields([
      { key: "strategy", label: "Strategy", kind: "select", defaultValue: "retry", options: [{ label: "Retry", value: "retry" }, { label: "Fallback", value: "fallback" }] },
      { key: "maxRetries", label: "Max Retries", kind: "number", defaultValue: 1, min: 0, max: 10, step: 1 },
    ]),
  }),
  futureBlock({
    type: "re_ranker",
    title: "Re-ranker",
    category: "Knowledge",
    kind: "knowledge",
    releasePhase: "phase2",
    description: "Coming soon: reorder retrieved chunks for better relevance.",
    integrationNotes:
      "Will sit after RAG retrieval and before Chatbot to improve source selection and citations.",
    accentColor: "#70d5a1",
    icon: "RR",
    inputs: [{ id: "knowledge", label: "Knowledge", direction: "input", dataTypes: ["knowledge", "json"], required: true }],
    outputs: [{ id: "knowledge", label: "Re-ranked Knowledge", direction: "output", dataTypes: ["knowledge", "json"] }],
    fields: fields([
      { key: "strategy", label: "Strategy", kind: "text", defaultValue: "cross-encoder" },
      { key: "topK", label: "Top K", kind: "number", defaultValue: 5, min: 1, max: 20, step: 1 },
    ]),
  }),
  futureBlock({
    type: "research_agent",
    title: "Research Agent",
    category: "AI",
    kind: "agent",
    releasePhase: "phase3",
    description: "Coming soon: orchestrate search, reading, and synthesis across many sources.",
    integrationNotes:
      "Will compose Web Search, Web Page Reader, RAG, and Summarizer into a higher-order agent loop.",
    accentColor: "#55c7d4",
    icon: "RA",
    inputs: [{ id: "query", label: "Query", direction: "input", dataTypes: ["chat", "text"], required: true }],
    outputs: [{ id: "report", label: "Report", direction: "output", dataTypes: ["text", "json", "knowledge"] }],
    fields: fields([
      { key: "depth", label: "Depth", kind: "select", defaultValue: "medium", options: [{ label: "Low", value: "low" }, { label: "Medium", value: "medium" }, { label: "High", value: "high" }] },
    ]),
  }),
  futureBlock({
    type: "sql_assistant",
    title: "SQL Assistant",
    category: "AI",
    kind: "agent",
    releasePhase: "phase3",
    description: "Coming soon: translate natural language into safe SQL assistance.",
    integrationNotes:
      "Will sit above Database Query and produce reviewed query plans before execution.",
    accentColor: "#6ea6ff",
    icon: "SA",
    inputs: [{ id: "question", label: "Question", direction: "input", dataTypes: ["chat", "text"], required: true }],
    outputs: [{ id: "query", label: "Query", direction: "output", dataTypes: ["text", "json"] }],
    fields: fields([
      { key: "dialect", label: "Dialect", kind: "text", defaultValue: "sqlite" },
      { key: "readOnly", label: "Read Only", kind: "toggle", defaultValue: true },
    ]),
  }),
  futureBlock({
    type: "database_query",
    title: "Database Query",
    category: "System",
    kind: "system",
    releasePhase: "phase3",
    description: "Coming soon: execute approved queries against connected databases.",
    integrationNotes:
      "Will consume SQL Assistant output and emit JSON result sets with audit logging.",
    accentColor: "#5d9cef",
    icon: "DQ",
    inputs: [{ id: "query", label: "Query", direction: "input", dataTypes: ["text", "json"], required: true }],
    outputs: [{ id: "rows", label: "Rows", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([
      { key: "connection", label: "Connection", kind: "text", defaultValue: "default-db" },
      { key: "timeoutSeconds", label: "Timeout Seconds", kind: "number", defaultValue: 30, min: 1, max: 600, step: 1 },
    ]),
  }),
  futureBlock({
    type: "email",
    title: "Email",
    category: "Outputs",
    kind: "output",
    releasePhase: "phase2",
    description: "Coming soon: send email notifications or summaries.",
    integrationNotes:
      "Will plug into provider adapters and reuse output payload formatting from Chat/JSON blocks.",
    accentColor: "#ffb347",
    icon: "EM",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [{ id: "status", label: "Status", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([
      { key: "to", label: "To", kind: "text", defaultValue: "" },
      { key: "subject", label: "Subject", kind: "text", defaultValue: "" },
    ]),
  }),
  futureBlock({
    type: "notification",
    title: "Notification",
    category: "Outputs",
    kind: "output",
    releasePhase: "phase2",
    description: "Coming soon: deliver lightweight push or webhook notifications.",
    integrationNotes:
      "Will expose provider adapters for Slack, webhooks, and app-native notifications.",
    accentColor: "#ffc36f",
    icon: "NT",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [{ id: "status", label: "Status", direction: "output", dataTypes: ["json", "text"] }],
    fields: fields([
      { key: "channel", label: "Channel", kind: "text", defaultValue: "default" },
      { key: "provider", label: "Provider", kind: "text", defaultValue: "webhook" },
    ]),
  }),
  futureBlock({
    type: "human_approval",
    title: "Human Approval",
    category: "Logic",
    kind: "logic",
    releasePhase: "phase3",
    description: "Coming soon: pause execution and wait for a person to approve or reject.",
    integrationNotes:
      "Will integrate with persistent run state and resumable execution for async approvals.",
    accentColor: "#ff9b5c",
    icon: "HA",
    inputs: [{ id: "request", label: "Request", direction: "input", dataTypes: ["text", "json", "chat"], required: true }],
    outputs: [
      { id: "approved", label: "Approved", direction: "output", dataTypes: ["any"] },
      { id: "rejected", label: "Rejected", direction: "output", dataTypes: ["any"] },
    ],
    fields: fields([
      { key: "assignee", label: "Assignee", kind: "text", defaultValue: "reviewer" },
      { key: "timeoutHours", label: "Timeout Hours", kind: "number", defaultValue: 24, min: 1, max: 168, step: 1 },
    ]),
  }),
  futureBlock({
    type: "guardrail",
    title: "Guardrail",
    category: "System",
    kind: "system",
    visibleInPalette: true,
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Validate inputs or outputs against simple blocked-term policy checks.",
    integrationNotes:
      "Will run before or after model calls and can feed into Error Handler or Human Approval.",
    accentColor: "#f26b6b",
    icon: "GR",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "json", "chat", "any"], required: true }],
    outputs: [
      { id: "safe", label: "Safe", direction: "output", dataTypes: ["any"] },
      { id: "blocked", label: "Blocked", direction: "output", dataTypes: ["any"] },
    ],
    fields: fields([
      { key: "blockedTerms", label: "Blocked Terms", kind: "textarea", defaultValue: "password\nsecret\napi key" },
    ]),
  }),
  futureBlock({
    type: "access_control",
    title: "Access Control",
    category: "System",
    kind: "system",
    releasePhase: "phase3",
    description: "Coming soon: enforce role- or tenant-based access before execution.",
    integrationNotes:
      "Will inspect session/user metadata and gate access to tools, memory, and published workflows.",
    accentColor: "#8b8fff",
    icon: "AC",
    inputs: [{ id: "request", label: "Request", direction: "input", dataTypes: ["json", "chat", "text"], required: true }],
    outputs: [{ id: "authorized", label: "Authorized", direction: "output", dataTypes: ["any"] }],
    fields: fields([
      { key: "policyName", label: "Policy Name", kind: "text", defaultValue: "default-access" },
      { key: "defaultRole", label: "Default Role", kind: "text", defaultValue: "viewer" },
    ]),
  }),
  futureBlock({
    type: "long_term_memory",
    title: "Long-Term Memory",
    category: "Memory",
    kind: "memory",
    visibleInPalette: true,
    implementationStatus: "implemented",
    releasePhase: "mvp",
    description: "Persist durable user or workflow facts beyond short chat windows.",
    integrationNotes:
      "Will extend the current conversation memory and RAG stores with profile- and fact-level recall.",
    accentColor: "#9a7dff",
    icon: "LM",
    inputs: [{ id: "content", label: "Content", direction: "input", dataTypes: ["text", "chat", "memory", "knowledge"] }],
    outputs: [{ id: "memory", label: "Memory", direction: "output", dataTypes: ["memory", "knowledge", "text"] }],
    fields: fields([
      { key: "scope", label: "Scope", kind: "text", defaultValue: "user" },
      { key: "maxFacts", label: "Max Facts", kind: "number", defaultValue: 20, min: 1, max: 200, step: 1 },
    ]),
  }),
];

export function getBlockDefinition(type: string): BlockDefinition | undefined {
  return blockDefinitions.find((definition) => definition.type === type);
}
